# Generated by Django 4.1 on 2026-06-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorartigos', '0003_alter_autor_table_alter_eixotecnologia_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='autor',
            name='biografia',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='eixotecnologia',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
